spring.application.name=To-Be-Read-literally
spring.datasource.url=jdbc:mariadb://192.168.178.104:3306/To-Be-Read-Literally
spring.datasource.username=alessia
spring.datasource.password=Panterarosa99!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
